- package-lock.json
- src/App.jsx
> Map structure

- .github/workflow/main.yaml
> Deployment

- .github/workflows/main.yaml
> yaml file with deplyoment created

- package-lock.json
- package.json
- src/test/App.test.jsx
- src/test/setup.js
- vite.config.js
Installed vitest and made a first test to always pass
> vitest install, first test passed

- package-lock.json
- package.json
- src/App.jsx
- src/main.jsx
Fixat navigering med routes, från react-router-dom, kommentar finns i App.jsx för när login är klar
> Navigation

- src/component/ui/Button.jsx
Added button to styling libary
> Add: Button

- src/App.jsx
- src/component/Category.jsx
- src/component/MovieItem.jsx
- src/data/movies.json
- src/pages/Categories.jsx
Skapat kategori sidan, kategori kompononent för rendering av enskild kategori samt MovieItem komponent som vi kan återanvända varje gång vi vill rendera en film. I MovieItem tänker jag att vi också lägger till eller skickar in bookmarking funktionen, plus klick funktion till filmview.
> Categories page

- index.html
- src/App.css
- src/component/RecomendedMovies.jsx
- src/component/ui/MoviesHomeRecomended.jsx
- src/component/ui/Navbar.jsx
- src/component/ui/Title.jsx
- src/index.css
- src/pages/home.jsx
Skapat styling kompontenter till navbar, button, title och filmer. Implementerat dessa på app.jsx samt på homepage
> Styling components UI

- .gitignore
- src/App.jsx
- src/pages/Categories.jsx
- src/test/Categories.test.jsx
- vite.config.js
Uppdaterat config så jest matchers funkar som de ska.
> Bug fixed for testing

- src/component/RecomendedMovies.jsx
- src/component/SearchBox.test.jsx
- have done tests for SearchBox
- added function in Recommended movies to not show trending movies here.
> SearchBox test and change recommended movies

- package.json
> Added homepage-url for deployment

- .eslintrc.cjs
- src/component/Category.jsx
- src/pages/Categories.test.jsx
- src/test/App.test.jsx
Fixed failed tests and linting problems in files i've worked in.
> Fixed tests and linting

- src/App.jsx
Changed to correct pathing on import "Home"
> Update App.jsx import to fix deployment

- src/App.jsx
- src/component/Login.jsx
- src/context/AuthCtx.jsx
- src/test/App.test.jsx
Missen i min trigger på context är åtgärdad samt test uppdatering och tagit bort överflödiga console.logs.
Är ajour med TEST.
> navigation & cleanup

- src/component/SearchBox.jsx
- src/component/SearchBox.test.jsx
- src/pages/Categories.jsx
- src/pages/Home.jsx
- src/pages/Home.test.jsx
Made the trending and recommended movies conditional. When theres no searchresult message is displayed. Fixed the tests in searchbox.
> Render only searched movies

- src/component/RecomendedMovies.jsx
- src/component/TrendingMovies.jsx
- src/component/ui/MovieCard.jsx
- src/component/ui/Navbar.jsx
- src/context/BookMarkCtx.jsx
- src/pages/BookMarks.jsx
Jag har lagt till localstorage så bookmarks är kvar vid reload, ändrat bookmark knapp så det går att lägga till en film utan att komma till filmens sida. m m.
> Adding localstorage to bookmark and remake bookmarkbutton

- package-lock.json
- package.json
- src/component/BookMarkButton.jsx
- src/component/ui/ButtonBookmark.jsx
- src/component/ui/MovieCard.jsx
- src/component/ui/Navbar.jsx
- src/context/AuthCtx.jsx
- src/context/BookMarkCtx.jsx
- src/main.jsx
- src/pages/BookMarks.jsx
- src/pages/Categories.test.jsx
- src/test/App.test.jsx
Rewrote context
added more integration tests
> Testing1.3

- src/components/BookMarkButton.test.jsx
- src/components/Category.test.jsx
- src/components/Login.test.jsx
- src/components/SearchBox.test.jsx
- src/pages/Categories.test.jsx
- src/pages/Home.test.jsx
- src/test/App.test.jsx
Set up user in all the tests and put them at the top. Updated tests to better matchers in tests. This is to have more secure tests and to have consistent coding style.
> Setup user and update tests

- src/components/ui/Navbar.jsx
- src/mobilecss/navbar.css
> Mobile navbar has now fixed position, and dosent scroll with the view

- src/context/AuthCtx.jsx
If you accidently navigated to "/login" you werent redirected to "/" or "HomePage". Now you this is working as intended.
> Hotfix login redirect

- src/App.css
- src/components/ui/TextParagraphBookmark.jsx
- src/mobilecss/button-bookmark.css
- src/mobilecss/navbar.css
- src/mobilecss/text-paragraph-bookmark.css
- src/mobilecss/title-line.css
- src/mobilecss/title.css
- src/mobilecss/two-columns.css
- src/pages/BookMarks.jsx
Updates on mobile view 
- Center title 
-  Movie detail done for mobil view
> Styling components UI latest

- src/context/AuthCtx.jsx
- src/index.css
- src/main.jsx
- src/mobilecss/body-text.css
- src/mobilecss/button-bookmark.css
- src/mobilecss/button.css
- src/mobilecss/movie-card.css
- src/mobilecss/navbar.css
- src/mobilecss/searchbar-container.css
- src/mobilecss/title-line.css
- src/mobilecss/title.css
- src/mobilecss/two-columns.css
Lint should not not complain about any files
> fixed linting errors

- src/components/RecomendedMovies.test.jsx
- src/components/TrendingMovies.test.jsx
Have redone the tests to be in the same style as the others, I have also added another test on Recommended movies to see that there are no Trending movies in this category.
> Remaking test for Rec and Trend

- src/mobilecss/button.css
Small change with button sizing for mobile
> Change: Sizing button

- src/components/MovieDetail.jsx
- src/components/MovieDetail.test.jsx
Actors name is now displayed with commas between
> Fixed missing commas between actors

- package-lock.json
- package.json
- src/App.css
- src/components/Carousel.css
- src/components/Carousel.jsx
- src/components/RecomendedMovies.jsx
- src/components/TrendingMovies.jsx
- src/components/TrendingMovies.test.jsx
- src/components/ui/Navbar.jsx
- src/index.css
- src/mobilecss/navbar.css
- src/test/App.test.jsx
Here is the carousel with working tests!
> Oscar carus
